### ISSUE TITLE
error probot on  gcf

### ISSUE THREAD

**Issue by rthadur** [probot/serverless-gcf#8]
Hi Getting this error after deploying to gcf , please assist 
TypeError: appFn is not a function |  
-- | --

**Comment by rthadur** [comment]
Thank you

**Comment by rthadur** [comment]
Hi jason ,please  let me know if you have any idea this : 
iam getting 200:OK response from bot but the body has this message : {"statusCode":500,"body":"{\"message\":{\"code\":401,\"message\":\"{\\\"message\\\":\\\"Missing 'issuer' claim ('iss') in assertion\\\",\\\"documentation_url\\\":\\\"https://developer.github.com/v3\\\"}\"}}"}

**Comment by xtremerui** [comment]
Hi, I came across this error as well. As a none pro node.js developer it took me some time to make it work. 

```
Github app root dir
  / index.js
  / handler.js
  / package.json
```

index.js
--
```javascript
module.exports = app = {...}
```

handler.js
--
```javascript
const { serverless } = require('@probot/serverless-gcf')
const appFn = require('./index').  // <--- notice this is different to the instruction
module.exports.probot = serverless(appFn)
```

package.json
```json
{
  "...": "...",
  "main": "handler.js"
}
```

So the idea is
1. the entrypoint of cloud fuction must be whatever file that requires serverless-gcf
2. when requiring the exported function in the entrypoint, the module name needs to match the file name i.e. `index` in above case.
